// docs/.vuepress/components/RouteEn.vue
<template>
<div class="routeBlock" :id="path">
  <p class="badge">
    <Badge text="Support BT" vertical="middle" type="tip" v-if="supportBT"/>
    <Badge text="Support Podcast" vertical="middle" type="tip" v-if="supportPodcast"/>
    <Badge text="Support Sci-Hub" vertical="middle" type="tip" v-if="supportScihub"/>
    <Badge text="Rely on Puppeteer" vertical="middle" type="warn" v-if="puppeteer"/>
    <a target="_blank" href="/en/faq.html" v-if="anticrawler"><Badge text="Strict anti-crawler policy" vertical="middle" type="warn"/></a>
    <a target="_blank" href="/en/install/" v-if="selfhost"><Badge text="Self-host only" vertical="middle" type="warn"/></a>
    <a target="_blank" href="https://github.com/DIYgod/RSSHub-Radar" v-if="radar"><Badge text="Support browser extension" vertical="middle" type="tip"/></a>
    <a target="_blank" href="https://github.com/Cay-Zhang/RSSBud" v-if="rssbud"><Badge text="Support RSSBud" vertical="middle" type="tip"/></a>
  </p>
  <p class="author">
    Author: <a v-for="uid in author.split(' ')" :href="`https://github.com/${uid}`" target="_blank"> @{{ uid }} </a>
  </p>
  <p  class="example">
    <span>Example:</span> <a :href="demoUrl" target="_blank">{{demoUrl}}</a> <img :src="'https://img.shields.io/website?label=status&style=flat-square&url=' + encodeURIComponent(encodeURI(demoUrl))">
  </p>
  <p class="path">
    Route: <code>{{ path }}</code>
  </p>
  <div v-if="path.match(/(?<=:).*?(?=\/|$)/g)">
  <p>
    Parameters:
  </p>
  <ul><li class="params" v-for="(item, index) in path.match(/(?<=:).*?(?=\/|$)/g)"><code>{{item.replace(/:|\?|\+|\*/g,'')}}</code>, {{{'?':'optional','*':'zero or more','+':'one or more'}[item[item.length-1]]||'required'}} - <span v-html="renderMarkdown(paramsDesc[index])"></span></li></ul>
  </div>
  <div v-else><p>Parameters: N/A</p></div>
  <slot></slot>
</div>
</template>
<script>
export default {
  props: {
    author: {
      type: String,
      default: 'DIYgod'
    },
    path: {
      type: String,
      required: true
    },
    example: {
      type: String,
      required: true
    },
    paramsDesc: {
      type: [Array, String],
      default: 'N/A'
    },
    anticrawler: {
      type: String,
      default: null
    },
    supportBT: {
      type: String,
      default: null
    },
    supportPodcast: {
      type: String,
      default: null
    },
    supportScihub: {
      type: String,
      default: null
    },
    radar: {
      type: String,
      default: null
    },
    rssbud: {
      type: String,
      default: null
    },
    selfhost: {
      type: String,
      default: null
    },
    puppeteer: {
      type: String,
      default: null
    }
  },
  methods: {
    renderMarkdown(item, inline = true) {
    const md = require('markdown-it')({
      html: true,
    });
      return inline ? md.renderInline(item) : md.render(item);
    },
  },
  computed: {
    demoUrl: function () {
      return 'https://rsshub.app'+ this.example
    }
  }
}
</script>

// website/src/components/RouteEn.tsx
import React from 'react';
import MarkdownIt from 'markdown-it';
import Badge from './Badge';

export default function Route(): JSX.Element {
    const {
        author = 'DIYgod',
        path = '',
        example = '',
        paramsDesc = 'N/A',
        anticrawler = null,
        supportBT = null,
        supportPodcast = null,
        supportScihub = null,
        radar = null,
        rssbud = null,
        selfhost = null,
        puppeteer = null,
    } = this.props;
    const demoUrl = 'https://rsshub.app' + example;
    const paramMatch = path.match(/(?<=:).*?(?=\/|$)/g);

    const renderMarkdown = (item, inline = true) => {
        const md = new MarkdownIt({
            html: true,
        });
        return inline ? md.renderInline(item) : md.render(item);
    };

    return (
        <div className="routeBlock" id={path}>
            <p className="badge">
                {supportBT && <Badge text="Support BT" type="tip" />}
                {supportPodcast && <Badge text="Support Podcast" type="tip" />}
                {supportScihub && <Badge text="Support Sci-Hub" type="tip" />}
                {puppeteer && <Badge text="Rely on Puppeteer" type="warn" />}
                {anticrawler && (
                    <a target="_blank" href="/faq.html">
                        <Badge text="Strict anti-crawler policy" type="warn" />
                    </a>
                )}
                {selfhost && (
                    <a target="_blank" href="/install/">
                        <Badge text="Self-host only" type="warn" />
                    </a>
                )}
                {radar && (
                    <a target="_blank" href="https://github.com/DIYgod/RSSHub-Radar">
                        <Badge text="Support browser extension" type="tip" />
                    </a>
                )}
                {rssbud && (
                    <a target="_blank" href="https://github.com/Cay-Zhang/RSSBud">
                        <Badge text="Support RSSBud" type="tip" />
                    </a>
                )}
            </p>
            <p className="author">
                Author:{' '}
                {author.split(' ').map((uid) => (
                    <a href={`https://github.com/${uid}`} target="_blank">
                        {' '}
                        @ {uid}{' '}
                    </a>
                ))}
            </p>
            <p className="example">
                <span>Example:</span>{' '}
                <a href={demoUrl} target="_blank">
                    {demoUrl}
                </a>
            </p>
            <p className="path">
                Route: <code>{path}</code>
            </p>
            {paramMatch ? (
                <div>
                    <p>Parameters:</p>
                    <ul>
                        {paramMatch.map((item, index) => (
                            <li className="params" key={index}>
                                <code>{item.replace(/:|\?|\+|\*/g, '')}</code>,
                                {{
                                    '?': 'optional',
                                    '*': 'zero or more',
                                    '+': 'one or more',
                                }[item[item.length - 1]] || 'required'}
                                -<span dangerouslySetInnerHTML={{ __html: renderMarkdown(paramsDesc[index]) }}></span>
                            </li>
                        ))}
                    </ul>
                </div>
            ) : (
                <p>Parameters: N/A</p>
            )}
        </div>
    );
}
